version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace/
    ports:
      - "8000:8000"
    command: python src/main.py
  proxy:
    image: nginx:latest
    container_name: proxy_container
    ports:
      - 80:80